name: Deploy ARM Template

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: MadWorldTools
          template: ../../MadWorld/MadWorld.Deployment/deploy-madworld.json
          additionalArguments: "--name deployment-madworld --mode Complete"