name: Deploy ARM Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        if: github.event_name == 'push'
        with:
         resourceGroupName: MadWorldTools
         template: MadWorld/MadWorld.Deployment/main-deploy.json
         deploymentMode: Complete
         additionalArguments: "--name deployment-madworld"
      - uses: azure/arm-deploy@v1
        if: github.event_name == 'pull_request'
        with:
          resourceGroupName: MadWorldTools
          template: MadWorld/MadWorld.Deployment/main-deploy.json
          deploymentMode: Validate
          additionalArguments: "--name deployment-madworld"
