name: Deploy ARM Template

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az deployment group create \
              --mode Complete \
              --name deployment-madworld \
              --resource-group MadWorldTools \
              --template-uri "MadWorld/MadWorld.Deployment/deploy-madworld.json"
            echo "Azure resource group deployed"
