name: Deploy ARM Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        name: Validate and Deploy ARM
        if: github.event_name == 'push'
        with:
         resourceGroupName: MadWorldTools
         deploymentName: deployment-madworld
         template: MadWorld/MadWorld.Deployment/main-deploy.json
         deploymentMode: Complete
         parameters: gitBranch=${{ github.head_ref || github.ref_name }} environmentTag=production
      - uses: azure/arm-deploy@v1
        name: Validate ARM only
        if: github.event_name == 'pull_request'
        with:
          resourceGroupName: MadWorldTools
          deploymentName: deployment-madworld
          template: MadWorld/MadWorld.Deployment/main-deploy.json
          deploymentMode: Validate
          parameters: gitBranch=${{ github.head_ref || github.ref_name }} environmentTag=production
